// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

package com.slightech.mynteye;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

/** Add-On are peripheral modules of our hardware */
public enum Addon {
    /** Infrared */
    INFRARED,
    /** Second infrared */
    INFRARED2,
    ;
}
