// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

package com.slightech.mynteye;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

/** Camera calibration model */
public enum CalibrationModel {
    /** Pinhole */
    PINHOLE,
    /** Equidistant: KANNALA_BRANDT */
    KANNALA_BRANDT,
    /** Unknow */
    UNKNOW,
    ;
}
