// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

package com.slightech.mynteye;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

/**
 * Capabilities define the full set of functionality that the device
 * might provide
 */
public enum Capability {
    /** Provides stereo stream */
    STEREO,
    /** Provide stereo color stream */
    STEREO_COLOR,
    /** Provides color stream */
    COLOR,
    /** Provides depth stream */
    DEPTH,
    /** Provides point cloud stream */
    POINTS,
    /** Provides fisheye stream */
    FISHEYE,
    /** Provides infrared stream */
    INFRARED,
    /** Provides second infrared stream */
    INFRARED2,
    /** Provides IMU (accelerometer, gyroscope) data */
    IMU,
    ;
}
