// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

package com.slightech.mynteye;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

/** Device USB information */
public final class DeviceUsbInfo {


    /*package*/ final int mVid;

    /*package*/ final int mPid;

    /*package*/ final int mFd;

    /*package*/ final int mBusNum;

    /*package*/ final int mDevNum;

    /*package*/ final String mUsbFs;

    /*package*/ final String mName;

    /*package*/ final String mSerial;

    public DeviceUsbInfo(
            int vid,
            int pid,
            int fd,
            int busNum,
            int devNum,
            @NonNull String usbFs,
            @NonNull String name,
            @NonNull String serial) {
        this.mVid = vid;
        this.mPid = pid;
        this.mFd = fd;
        this.mBusNum = busNum;
        this.mDevNum = devNum;
        this.mUsbFs = usbFs;
        this.mName = name;
        this.mSerial = serial;
    }

    /** Vendor id */
    public int getVid() {
        return mVid;
    }

    /** Product id */
    public int getPid() {
        return mPid;
    }

    /** File descriptor */
    public int getFd() {
        return mFd;
    }

    /** Bus number */
    public int getBusNum() {
        return mBusNum;
    }

    /** Dev number */
    public int getDevNum() {
        return mDevNum;
    }

    /** Usb file system path */
    @NonNull
    public String getUsbFs() {
        return mUsbFs;
    }

    /** Product name */
    @NonNull
    public String getName() {
        return mName;
    }

    /** Serial number */
    @NonNull
    public String getSerial() {
        return mSerial;
    }

    @Override
    public String toString() {
        return "DeviceUsbInfo{" +
                "mVid=" + mVid +
                "," + "mPid=" + mPid +
                "," + "mFd=" + mFd +
                "," + "mBusNum=" + mBusNum +
                "," + "mDevNum=" + mDevNum +
                "," + "mUsbFs=" + mUsbFs +
                "," + "mName=" + mName +
                "," + "mSerial=" + mSerial +
        "}";
    }

}
