// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

package com.slightech.mynteye;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

/** Device USB information */
public final class DeviceUsbInfo {


    /*package*/ final int mIndex;

    /*package*/ final String mName;

    /*package*/ final String mSn;

    public DeviceUsbInfo(
            int index,
            @NonNull String name,
            @NonNull String sn) {
        this.mIndex = index;
        this.mName = name;
        this.mSn = sn;
    }

    /** Device index */
    public int getIndex() {
        return mIndex;
    }

    /** Device name */
    @NonNull
    public String getName() {
        return mName;
    }

    /** Device serial number */
    @NonNull
    public String getSn() {
        return mSn;
    }

    @Override
    public String toString() {
        return "DeviceUsbInfo{" +
                "mIndex=" + mIndex +
                "," + "mName=" + mName +
                "," + "mSn=" + mSn +
        "}";
    }

}
