// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

package com.slightech.mynteye;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import java.util.ArrayList;

/** Extrinsics, represent how the different datas are connected */
public final class Extrinsics {


    /*package*/ final ArrayList<Double> mRotation;

    /*package*/ final ArrayList<Double> mTranslation;

    public Extrinsics(
            @NonNull ArrayList<Double> rotation,
            @NonNull ArrayList<Double> translation) {
        this.mRotation = rotation;
        this.mTranslation = translation;
    }

    /** Rotation matrix, 3x3 */
    @NonNull
    public ArrayList<Double> getRotation() {
        return mRotation;
    }

    /** Translation vector, 1x3 */
    @NonNull
    public ArrayList<Double> getTranslation() {
        return mTranslation;
    }

    @Override
    public String toString() {
        return "Extrinsics{" +
                "mRotation=" + mRotation +
                "," + "mTranslation=" + mTranslation +
        "}";
    }

}
