// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

package com.slightech.mynteye;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

/** Formats define how each stream can be encoded */
public enum Format {
    /** Greyscale, 8 bits per pixel */
    GREY,
    /** YUV 4:2:2, 16 bits per pixel */
    YUYV,
    /** BGR 8:8:8, 24 bits per pixel */
    BGR888,
    /** RGB 8:8:8, 24 bits per pixel */
    RGB888,
    ;
}
