// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye.djinni

package com.slightech.mynteye;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

public enum Format {
    GREY,
    YUYV,
    BGR888,
    RGB888,
    ;
}
