// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

package com.slightech.mynteye;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

/** Image data */
public final class ImgData {


    /*package*/ final long mFrameId;

    /*package*/ final long mTimestamp;

    /*package*/ final long mExposureTime;

    public ImgData(
            long frameId,
            long timestamp,
            long exposureTime) {
        this.mFrameId = frameId;
        this.mTimestamp = timestamp;
        this.mExposureTime = exposureTime;
    }

    /** Image frame id */
    public long getFrameId() {
        return mFrameId;
    }

    /** Image timestamp in 1us */
    public long getTimestamp() {
        return mTimestamp;
    }

    /** Image exposure time, virtual value in [1, 480] */
    public long getExposureTime() {
        return mExposureTime;
    }

    @Override
    public String toString() {
        return "ImgData{" +
                "mFrameId=" + mFrameId +
                "," + "mTimestamp=" + mTimestamp +
                "," + "mExposureTime=" + mExposureTime +
        "}";
    }

}
