// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

package com.slightech.mynteye;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

/** Camera info fields are read-only strings that can be queried from the device */
public enum Info {
    /** Device name */
    DEVICE_NAME,
    /** Serial number */
    SERIAL_NUMBER,
    /** Firmware version */
    FIRMWARE_VERSION,
    /** Hardware version */
    HARDWARE_VERSION,
    /** Spec version */
    SPEC_VERSION,
    /** Lens type */
    LENS_TYPE,
    /** IMU type */
    IMU_TYPE,
    /** Nominal baseline */
    NOMINAL_BASELINE,
    ;
}
