// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

package com.slightech.mynteye;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

/** Device model */
public enum Model {
    /** Standard */
    STANDARD,
    /** Standard 2 */
    STANDARD2,
    /** Standard 210a */
    STANDARD210A,
    /** Standard 200b */
    STANDARD200B,
    ;
}
