// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

package com.slightech.mynteye;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

/** Motion intrinsics, including accelerometer and gyroscope */
public final class MotionIntrinsics {


    /*package*/ final ImuIntrinsics mAccel;

    /*package*/ final ImuIntrinsics mGyro;

    public MotionIntrinsics(
            @NonNull ImuIntrinsics accel,
            @NonNull ImuIntrinsics gyro) {
        this.mAccel = accel;
        this.mGyro = gyro;
    }

    /** Accelerometer intrinsics */
    @NonNull
    public ImuIntrinsics getAccel() {
        return mAccel;
    }

    /** Gyroscope intrinsics */
    @NonNull
    public ImuIntrinsics getGyro() {
        return mGyro;
    }

    @Override
    public String toString() {
        return "MotionIntrinsics{" +
                "mAccel=" + mAccel +
                "," + "mGyro=" + mGyro +
        "}";
    }

}
