// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

package com.slightech.mynteye;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

/** Source allows the user to choose which data to be captured */
public enum Source {
    /** Video streaming of stereo, color, depth, etc. */
    VIDEO_STREAMING,
    /** Motion tracking of IMU (accelerometer, gyroscope) */
    MOTION_TRACKING,
    /** Enable everything together */
    ALL,
    ;
}
