// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

package com.slightech.mynteye;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

/** Streams define different type of data */
public enum Stream {
    /** Left stream */
    LEFT,
    /** Right stream */
    RIGHT,
    ;
}
