// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

package com.slightech.mynteye;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

/** Stream request */
public final class StreamRequest {


    /*package*/ final int mIndex;

    /*package*/ final int mWidth;

    /*package*/ final int mHeight;

    /*package*/ final Format mFormat;

    /*package*/ final int mFps;

    public StreamRequest(
            int index,
            int width,
            int height,
            @NonNull Format format,
            int fps) {
        this.mIndex = index;
        this.mWidth = width;
        this.mHeight = height;
        this.mFormat = format;
        this.mFps = fps;
    }

    /** Stream index */
    public int getIndex() {
        return mIndex;
    }

    /** Stream width in pixels */
    public int getWidth() {
        return mWidth;
    }

    /** Stream height in pixels */
    public int getHeight() {
        return mHeight;
    }

    /** Stream pixel format */
    @NonNull
    public Format getFormat() {
        return mFormat;
    }

    /** Stream frames per second */
    public int getFps() {
        return mFps;
    }

    @Override
    public String toString() {
        return "StreamRequest{" +
                "mIndex=" + mIndex +
                "," + "mWidth=" + mWidth +
                "," + "mHeight=" + mHeight +
                "," + "mFormat=" + mFormat +
                "," + "mFps=" + mFps +
        "}";
    }

}
