// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include <functional>

namespace mynteye_jni {

enum class Addon : int {
    /** Infrared */
    INFRARED,
    /** Second infrared */
    INFRARED2,
};

}  // namespace mynteye_jni

namespace std {

template <>
struct hash<::mynteye_jni::Addon> {
    size_t operator()(::mynteye_jni::Addon type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
