// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include <functional>

namespace mynteye_jni {

enum class Capability : int {
    /** Provides stereo stream */
    STEREO,
    /** Provide stereo color stream */
    STEREO_COLOR,
    /** Provides color stream */
    COLOR,
    /** Provides depth stream */
    DEPTH,
    /** Provides point cloud stream */
    POINTS,
    /** Provides fisheye stream */
    FISHEYE,
    /** Provides infrared stream */
    INFRARED,
    /** Provides second infrared stream */
    INFRARED2,
    /** Provides IMU (accelerometer, gyroscope) data */
    IMU,
};

}  // namespace mynteye_jni

namespace std {

template <>
struct hash<::mynteye_jni::Capability> {
    size_t operator()(::mynteye_jni::Capability type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
