// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye.djinni

#pragma once

#include <memory>
#include <vector>

namespace mynteye_jni {

struct DeviceUsbInfo;
struct StreamRequest;

class Device {
public:
    virtual ~Device() {}

    static std::vector<DeviceUsbInfo> Query();

    static std::shared_ptr<Device> Create(const DeviceUsbInfo & info);

    virtual std::vector<StreamRequest> GetStreamRequests() = 0;

    virtual void ConfigStreamRequest(const StreamRequest & request) = 0;

    virtual void Start() = 0;

    virtual void Stop() = 0;
};

}  // namespace mynteye_jni
