// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include <cstdint>
#include <string>
#include <utility>

namespace mynteye_jni {

/** Device USB information */
struct DeviceUsbInfo final {
    /** Device index */
    int32_t index;
    /** Device name */
    std::string name;
    /** Device serial number */
    std::string sn;

    DeviceUsbInfo(int32_t index_,
                  std::string name_,
                  std::string sn_)
    : index(std::move(index_))
    , name(std::move(name_))
    , sn(std::move(sn_))
    {}
};

}  // namespace mynteye_jni
