// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include <utility>
#include <vector>

namespace mynteye_jni {

/** Extrinsics, represent how the different datas are connected */
struct Extrinsics final {
    /** Rotation matrix, 3x3 */
    std::vector<double> rotation;
    /** Translation vector, 1x3 */
    std::vector<double> translation;

    Extrinsics(std::vector<double> rotation_,
               std::vector<double> translation_)
    : rotation(std::move(rotation_))
    , translation(std::move(translation_))
    {}
};

}  // namespace mynteye_jni
