// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye.djinni

#pragma once

#include <functional>

namespace mynteye_jni {

enum class Format : int {
    GREY,
    YUYV,
    BGR888,
    RGB888,
};

}  // namespace mynteye_jni

namespace std {

template <>
struct hash<::mynteye_jni::Format> {
    size_t operator()(::mynteye_jni::Format type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
