// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include <cstdint>
#include <vector>

namespace mynteye_jni {

enum class Format;

/** Frame with raw data */
class Frame {
public:
    virtual ~Frame() {}

    /** Get the width */
    virtual int32_t Width() = 0;

    /** Get the height */
    virtual int32_t Height() = 0;

    /** Get the pixel format */
    virtual ::mynteye_jni::Format Format() = 0;

    /** Get the size */
    virtual int32_t Size() = 0;

    /** Get the data */
    virtual std::vector<uint8_t> Data() = 0;
};

}  // namespace mynteye_jni
