// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace mynteye_jni {

/** Image data */
struct ImgData final {
    /** Image frame id */
    int64_t frame_id;
    /** Image timestamp in 1us */
    int64_t timestamp;
    /** Image exposure time, virtual value in [1, 480] */
    int64_t exposure_time;

    ImgData(int64_t frame_id_,
            int64_t timestamp_,
            int64_t exposure_time_)
    : frame_id(std::move(frame_id_))
    , timestamp(std::move(timestamp_))
    , exposure_time(std::move(exposure_time_))
    {}
};

}  // namespace mynteye_jni
