// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include <utility>
#include <vector>

namespace mynteye_jni {

/** IMU intrinsics: scale, drift and variances */
struct ImuIntrinsics final {
    /**
     * Scale matrix 3x3
     *  Scale X     cross axis  cross axis
     *  cross axis  Scale Y     cross axis
     *  cross axis  cross axis  Scale Z
     */
    std::vector<double> scale;
    /** Zero-drift: X, Y, Z 1x3 */
    std::vector<double> drift;
    /** Noise density variances 1x3 */
    std::vector<double> noise;
    /** Random walk variances 1x3 */
    std::vector<double> bias;

    ImuIntrinsics(std::vector<double> scale_,
                  std::vector<double> drift_,
                  std::vector<double> noise_,
                  std::vector<double> bias_)
    : scale(std::move(scale_))
    , drift(std::move(drift_))
    , noise(std::move(noise_))
    , bias(std::move(bias_))
    {}
};

}  // namespace mynteye_jni
