// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include <functional>

namespace mynteye_jni {

enum class Info : int {
    /** Device name */
    DEVICE_NAME,
    /** Serial number */
    SERIAL_NUMBER,
    /** Firmware version */
    FIRMWARE_VERSION,
    /** Hardware version */
    HARDWARE_VERSION,
    /** Spec version */
    SPEC_VERSION,
    /** Lens type */
    LENS_TYPE,
    /** IMU type */
    IMU_TYPE,
    /** Nominal baseline */
    NOMINAL_BASELINE,
};

}  // namespace mynteye_jni

namespace std {

template <>
struct hash<::mynteye_jni::Info> {
    size_t operator()(::mynteye_jni::Info type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
