// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include <functional>

namespace mynteye_jni {

enum class Model : int {
    /** Standard */
    STANDARD,
    /** Standard 2 */
    STANDARD2,
    /** Standard 210a */
    STANDARD210A,
    /** Standard 200b */
    STANDARD200B,
};

}  // namespace mynteye_jni

namespace std {

template <>
struct hash<::mynteye_jni::Model> {
    size_t operator()(::mynteye_jni::Model type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
