// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

namespace mynteye_jni {

struct ImuData;

/** Device motion data */
class MotionData {
public:
    virtual ~MotionData() {}

    virtual ImuData Imu() = 0;
};

}  // namespace mynteye_jni
