// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace mynteye_jni {

/** Option info */
struct OptionInfo final {
    /** Minimum value */
    int32_t min;
    /** Maximum value */
    int32_t max;
    /** Default value */
    int32_t def;

    OptionInfo(int32_t min_,
               int32_t max_,
               int32_t def_)
    : min(std::move(min_))
    , max(std::move(max_))
    , def(std::move(def_))
    {}
};

}  // namespace mynteye_jni
