// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include <functional>

namespace mynteye_jni {

enum class Stream : int {
    /** Left stream */
    LEFT,
    /** Right stream */
    RIGHT,
};

}  // namespace mynteye_jni

namespace std {

template <>
struct hash<::mynteye_jni::Stream> {
    size_t operator()(::mynteye_jni::Stream type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
