// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include "format.hpp"
#include <cstdint>
#include <utility>

namespace mynteye_jni {

/** Stream request */
struct StreamRequest final {
    /** Stream index */
    int32_t index;
    /** Stream width in pixels */
    int32_t width;
    /** Stream height in pixels */
    int32_t height;
    /** Stream pixel format */
    Format format;
    /** Stream frames per second */
    int32_t fps;

    StreamRequest(int32_t index_,
                  int32_t width_,
                  int32_t height_,
                  Format format_,
                  int32_t fps_)
    : index(std::move(index_))
    , width(std::move(width_))
    , height(std::move(height_))
    , format(std::move(format_))
    , fps(std::move(fps_))
    {}
};

}  // namespace mynteye_jni
