// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#include "NativeImuIntrinsics.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeImuIntrinsics::NativeImuIntrinsics() = default;

NativeImuIntrinsics::~NativeImuIntrinsics() = default;

auto NativeImuIntrinsics::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeImuIntrinsics>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::List<::djinni::F64>::fromCpp(jniEnv, c.scale)),
                                                           ::djinni::get(::djinni::List<::djinni::F64>::fromCpp(jniEnv, c.drift)),
                                                           ::djinni::get(::djinni::List<::djinni::F64>::fromCpp(jniEnv, c.noise)),
                                                           ::djinni::get(::djinni::List<::djinni::F64>::fromCpp(jniEnv, c.bias)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeImuIntrinsics::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 5);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeImuIntrinsics>::get();
    return {::djinni::List<::djinni::F64>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mScale)),
            ::djinni::List<::djinni::F64>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mDrift)),
            ::djinni::List<::djinni::F64>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mNoise)),
            ::djinni::List<::djinni::F64>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mBias))};
}

}  // namespace djinni_generated
