// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include "djinni_support.hpp"
#include "stream.hpp"

namespace djinni_generated {

class NativeStream final : ::djinni::JniEnum {
public:
    using CppType = ::mynteye_jni::Stream;
    using JniType = jobject;

    using Boxed = NativeStream;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeStream>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeStream>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeStream() : JniEnum("com/slightech/mynteye/Stream") {}
    friend ::djinni::JniClass<NativeStream>;
};

}  // namespace djinni_generated
