// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include "djinni_support.hpp"
#include "format.hpp"

namespace djinni_generated {

class NativeFormat final : ::djinni::JniEnum {
public:
    using CppType = ::mynteye_jni::Format;
    using JniType = jobject;

    using Boxed = NativeFormat;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeFormat>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeFormat>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeFormat() : JniEnum("com/slightech/mynteye/Format") {}
    friend ::djinni::JniClass<NativeFormat>;
};

}  // namespace djinni_generated
