// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include "calibration_model.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeCalibrationModel final : ::djinni::JniEnum {
public:
    using CppType = ::mynteye_jni::CalibrationModel;
    using JniType = jobject;

    using Boxed = NativeCalibrationModel;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeCalibrationModel>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeCalibrationModel>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeCalibrationModel() : JniEnum("com/slightech/mynteye/CalibrationModel") {}
    friend ::djinni::JniClass<NativeCalibrationModel>;
};

}  // namespace djinni_generated
