// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include "djinni_support.hpp"
#include "info.hpp"

namespace djinni_generated {

class NativeInfo final : ::djinni::JniEnum {
public:
    using CppType = ::mynteye_jni::Info;
    using JniType = jobject;

    using Boxed = NativeInfo;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeInfo>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeInfo>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeInfo() : JniEnum("com/slightech/mynteye/Info") {}
    friend ::djinni::JniClass<NativeInfo>;
};

}  // namespace djinni_generated
