// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include "djinni_support.hpp"
#include "motion_data.hpp"

namespace djinni_generated {

class NativeMotionData final : ::djinni::JniInterface<::mynteye_jni::MotionData, NativeMotionData> {
public:
    using CppType = std::shared_ptr<::mynteye_jni::MotionData>;
    using CppOptType = std::shared_ptr<::mynteye_jni::MotionData>;
    using JniType = jobject;

    using Boxed = NativeMotionData;

    ~NativeMotionData();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeMotionData>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeMotionData>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeMotionData();
    friend ::djinni::JniClass<NativeMotionData>;
    friend ::djinni::JniInterface<::mynteye_jni::MotionData, NativeMotionData>;

};

}  // namespace djinni_generated
