// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include "djinni_support.hpp"
#include "stream_data.hpp"

namespace djinni_generated {

class NativeStreamData final : ::djinni::JniInterface<::mynteye_jni::StreamData, NativeStreamData> {
public:
    using CppType = std::shared_ptr<::mynteye_jni::StreamData>;
    using CppOptType = std::shared_ptr<::mynteye_jni::StreamData>;
    using JniType = jobject;

    using Boxed = NativeStreamData;

    ~NativeStreamData();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeStreamData>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeStreamData>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeStreamData();
    friend ::djinni::JniClass<NativeStreamData>;
    friend ::djinni::JniInterface<::mynteye_jni::StreamData, NativeStreamData>;

};

}  // namespace djinni_generated
