// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include "djinni_support.hpp"
#include "option_info.hpp"

namespace djinni_generated {

class NativeOptionInfo final {
public:
    using CppType = ::mynteye_jni::OptionInfo;
    using JniType = jobject;

    using Boxed = NativeOptionInfo;

    ~NativeOptionInfo();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeOptionInfo();
    friend ::djinni::JniClass<NativeOptionInfo>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/slightech/mynteye/OptionInfo") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(III)V") };
    const jfieldID field_mMin { ::djinni::jniGetFieldID(clazz.get(), "mMin", "I") };
    const jfieldID field_mMax { ::djinni::jniGetFieldID(clazz.get(), "mMax", "I") };
    const jfieldID field_mDef { ::djinni::jniGetFieldID(clazz.get(), "mDef", "I") };
};

}  // namespace djinni_generated
