// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include "capability.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeCapability final : ::djinni::JniEnum {
public:
    using CppType = ::mynteye_jni::Capability;
    using JniType = jobject;

    using Boxed = NativeCapability;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeCapability>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeCapability>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeCapability() : JniEnum("com/slightech/mynteye/Capability") {}
    friend ::djinni::JniClass<NativeCapability>;
};

}  // namespace djinni_generated
