// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye.djinni

#pragma once

#include "device.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeDevice final : ::djinni::JniInterface<::mynteye_jni::Device, NativeDevice> {
public:
    using CppType = std::shared_ptr<::mynteye_jni::Device>;
    using CppOptType = std::shared_ptr<::mynteye_jni::Device>;
    using JniType = jobject;

    using Boxed = NativeDevice;

    ~NativeDevice();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeDevice>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeDevice>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeDevice();
    friend ::djinni::JniClass<NativeDevice>;
    friend ::djinni::JniInterface<::mynteye_jni::Device, NativeDevice>;

};

}  // namespace djinni_generated
