// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#include "NativeImuData.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeImuData::NativeImuData() = default;

NativeImuData::~NativeImuData() = default;

auto NativeImuData::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeImuData>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.frame_id)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.flag)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.timestamp)),
                                                           ::djinni::get(::djinni::List<::djinni::F64>::fromCpp(jniEnv, c.accel)),
                                                           ::djinni::get(::djinni::List<::djinni::F64>::fromCpp(jniEnv, c.gyro)),
                                                           ::djinni::get(::djinni::F64::fromCpp(jniEnv, c.temperature)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeImuData::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 7);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeImuData>::get();
    return {::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mFrameId)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mFlag)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mTimestamp)),
            ::djinni::List<::djinni::F64>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mAccel)),
            ::djinni::List<::djinni::F64>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mGyro)),
            ::djinni::F64::toCpp(jniEnv, jniEnv->GetDoubleField(j, data.field_mTemperature))};
}

}  // namespace djinni_generated
