// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include "addon.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeAddon final : ::djinni::JniEnum {
public:
    using CppType = ::mynteye_jni::Addon;
    using JniType = jobject;

    using Boxed = NativeAddon;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeAddon>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeAddon>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeAddon() : JniEnum("com/slightech/mynteye/Addon") {}
    friend ::djinni::JniClass<NativeAddon>;
};

}  // namespace djinni_generated
