// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include "djinni_support.hpp"
#include "option.hpp"

namespace djinni_generated {

class NativeOption final : ::djinni::JniEnum {
public:
    using CppType = ::mynteye_jni::Option;
    using JniType = jobject;

    using Boxed = NativeOption;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeOption>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeOption>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeOption() : JniEnum("com/slightech/mynteye/Option") {}
    friend ::djinni::JniClass<NativeOption>;
};

}  // namespace djinni_generated
