// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include "djinni_support.hpp"
#include "source.hpp"

namespace djinni_generated {

class NativeSource final : ::djinni::JniEnum {
public:
    using CppType = ::mynteye_jni::Source;
    using JniType = jobject;

    using Boxed = NativeSource;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeSource>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeSource>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeSource() : JniEnum("com/slightech/mynteye/Source") {}
    friend ::djinni::JniClass<NativeSource>;
};

}  // namespace djinni_generated
