// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mynteye_types.djinni

#pragma once

#include "djinni_support.hpp"
#include "frame.hpp"

namespace djinni_generated {

class NativeFrame final : ::djinni::JniInterface<::mynteye_jni::Frame, NativeFrame> {
public:
    using CppType = std::shared_ptr<::mynteye_jni::Frame>;
    using CppOptType = std::shared_ptr<::mynteye_jni::Frame>;
    using JniType = jobject;

    using Boxed = NativeFrame;

    ~NativeFrame();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeFrame>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeFrame>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeFrame();
    friend ::djinni::JniClass<NativeFrame>;
    friend ::djinni::JniInterface<::mynteye_jni::Frame, NativeFrame>;

};

}  // namespace djinni_generated
